const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Bullet.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{janela: 0},
	{Solid: 0},
	{suporte: 0},
	{Flash: 0},
	{bau: 0},
	{Platform: 0},
	{caixa: 0},
	{porta: 0},
	{chave: 0},
	{bomba: 0},
	{cristal: 0},
	{cutsceneAndando: 0},
	{ScrollTo: 0},
	{jogador_Rei: 0},
	{sensorSolido: 0},
	{direcao: 0},
	{porco_patrulheiro: 0},
	{sensor_patrulheiro_direita: 0},
	{sensor_patrulheiro_esquerda: 0},
	{porco_canhao: 0},
	{canhao: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{bala: 0},
	{sensor_canhao: 0},
	{vida_hud: 0},
	{itens_hud: 0},
	{black_blackground: 0},
	{jogador_diálogo: 0},
	{SpriteFont: 0},
	{chefao: 0},
	{Audio: 0},
	{nomemenu: 0},
	{jogar: 0},
	{portafase2: 0},
	{portafase3: 0},
	{escuro: 0},
	{Pin: 0},
	{foco_de_luz: 0},
	{run: 0},
	{dead: 0},
	{sensor_tp: 0},
	{load: 0},
	{sprsense2: 0},
	{Keyboard: 0},
	{slime: 0},
	{atacando: 0},
	{estado: 0},
	{jogador_Princesa: 0},
	{jogador_Mago: 0},
	{cutsceneAndando2: 0},
	{jogador_Bruxa: 0},
	{comunicador: 0},
	{jogador_Elfo: 0},
	{Tilemap2: 0},
	{Woods: 0},
	{Woods2: 0},
	{BG: 0},
	{flecha: 0},
	{cela: 0},
	{tocha: 0},
	{podeCausarDano: 0},
	{jogador_Lady: 0},
	{jaQuebrou: 0},
	{celaQuebravel: 0},
	{vida_hudLady: 0},
	{portal: 0},
	{vida_hudMorgana: 0},
	{creditos: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{pause: 0},
	{Resume: 0},
	{Salvar: 0},
	{vidas: 0},
	{vidasMorgana: 0},
	{vidasLady: 0},
	{puxando: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	janela: class extends self.ISpriteInstance {},
	suporte: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	jogador_Rei: class extends self.ISpriteInstance {},
	sensorSolido: class extends self.ISpriteInstance {},
	porco_patrulheiro: class extends self.ISpriteInstance {},
	sensor_patrulheiro_direita: class extends self.ISpriteInstance {},
	sensor_patrulheiro_esquerda: class extends self.ISpriteInstance {},
	porco_canhao: class extends self.ISpriteInstance {},
	canhao: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	sensor_canhao: class extends self.ISpriteInstance {},
	vida_hud: class extends self.ISpriteInstance {},
	itens_hud: class extends self.ISpriteInstance {},
	black_blackground: class extends self.ISpriteInstance {},
	jogador_diálogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	chave: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	nomemenu: class extends self.ITextInstance {},
	jogar: class extends self.IButtonInstance {},
	portafase2: class extends self.ISpriteInstance {},
	portafase3: class extends self.ISpriteInstance {},
	cristal: class extends self.ISpriteInstance {},
	escuro: class extends self.ISpriteInstance {},
	foco_de_luz: class extends self.ISpriteInstance {},
	run: class extends self.ITextInstance {},
	dead: class extends self.ITextInstance {},
	sensor_tp: class extends self.ISpriteInstance {},
	load: class extends self.IButtonInstance {},
	sprsense2: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	slime: class extends self.ISpriteInstance {},
	jogador_Princesa: class extends self.ISpriteInstance {},
	jogador_Mago: class extends self.ISpriteInstance {},
	jogador_Bruxa: class extends self.ISpriteInstance {},
	jogador_Elfo: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Woods: class extends self.ISpriteInstance {},
	Woods2: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	flecha: class extends self.ISpriteInstance {},
	cela: class extends self.ISpriteInstance {},
	tocha: class extends self.ISpriteInstance {},
	jogador_Lady: class extends self.ISpriteInstance {},
	celaQuebravel: class extends self.ISpriteInstance {},
	vida_hudLady: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	vida_hudMorgana: class extends self.ISpriteInstance {},
	creditos: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	pause: class extends self.ITextInstance {},
	Resume: class extends self.IButtonInstance {},
	Salvar: class extends self.IButtonInstance {}
}